### ISSUE TITLE
我遇到指令沒有辦法順利執行,請教一下該怎麼解決?

### ISSUE THREAD

**Issue by o920130130** [ItzMiracleOwO/surface-ubuntu#1]
你好,我手邊也是有一台surface book2 15吋
最近剛安裝好了ubuntu 18.04
我想要解決gpu在ubuntu運作的問題以免電腦過熱 
我遇到指令沒有辦法順利執行,請教一下該怎麼解決?
我已經把我的問題整理在Google文件中,如果你有Google的帳號就可以連這個網址進入這個文檔
https://docs.google.com/document/d/1ILN96SkBzF9I7NUwV0rC7qpSceJNb1KCn28Fkapv5J4/edit?usp=sharing

下載預建內核
1.複製h這個專案到你的電腦:
paul@paul-Surface-Book-2:~/linux-stable$  git clone --depth 1 https://github.com/miracl-cutelemon173/surface-ubuntu/blob/main/README.MD
Cloning into 'README.MD'...

fatal: repository 'https://github.com/miracl-cutelemon173/surface-ubuntu/blob/main/README.MD/' not found
找不到檔案

2.以後還沒有執行
從源代碼編譯內核 
1.2都已經執行完畢

3.檢查您要定位的內核版本（替換為目標版本）:
paul@paul-Surface-Book-2:~/linux-stable$ git checkout v5.y.z
error: pathspec 'v5.y.z' did not match any file(s) known to git.

4.應用linux-surface存儲庫中的內核補丁（這一步，並假設您將其克隆到〜/ linux-surface中）:
paul@paul-Surface-Book-2:~/linux-stable$ for i in ~/linux-surface/patches/[VERSION]/*.patch; do patch -p1 < $i; done
bash: /home/paul/linux-surface/patches/[VERSION]/*.patch: No such file or directory

5.以後還沒有執行

**Comment by ItzMiracleOwO** [comment]
你好
請改爲使用以下指令:
`git clone https://github.com/ItzMiracleOwO/surface-ubuntu/`
並再試一次

對您造成了不便 我們深感遺憾

**Comment by o920130130** [comment]
你好
非常感謝你的協助 ,稍早的時候已經按照下載預建內核的流程安裝完畢了
下載預建內核

   1.

   複製這個專案到你的電腦:

git clone https://github.com/ItzMiracleOwO/surface-ubuntu



   1.

   進入這個專案的路徑:

cd linux-surface



   1.

   使用指令:

sudo sh setup.sh

已經順利安裝了 ,並且重新啟動


   1. 請教一下我要如何確認gpu,觸控的功能的驅動程式已經安裝了?剛剛我有嘗試觸控的功能但是似乎沒有反應, 平板背後的溫度還是40~50度左右
   2. 這兩個項目(下載預建內核,從源代碼編譯內核)兩種選一種來操作就可以了,對不對?
   3. 我想知道這一段命令格式是如何使用的,不知道是不是我理解的這個範例,如果我的理解是錯的請跟我說好嗎謝謝


   - sudo dpkg -i linux-headers-[版本].deb linux-image-[版本].deb
   linux-libc-dev-[版本].deb

EX.
*sudo dpkg -i linux-headers-5.10.0.deb
linux-image-generic_5.4.0.26.32_arm64.deb
linux-libc-dev-4.4.0-174.204_amd64.deb*

以上再請協助回覆了感謝你的幫忙






ItzMiracleOwO ***@***.***> 於 2021年8月8日 週日 下午5:31寫道：

**Comment by ItzMiracleOwO** [comment]
您好
安裝內核與執行專案中的setup.sh是不同的
安裝內核不會幫你安裝Surface電腦需要的驅動
但執行本專案會安裝驅動以及最新版本的內核

**Comment by ItzMiracleOwO** [comment]
在執行我們的專案後就不需要進行安裝內核的操作了

**Comment by ItzMiracleOwO** [comment]
由於您長時間沒有回復 我們將會關閉這個提問 感謝您對專案的支持

**Comment by ItzMiracleOwO** [comment]
由於您長時間沒有回復 我們將會關閉本提問 感謝您對專案的支持
